name: Building, Testing and Deploy Render

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
 workflow_dispatch: 

jobs:

 build-and-test-unit:
  runs-on: ubuntu-latest

  steps:
  - name: Copy the source code
    uses: actions/Checkout@v4
  - name: Use Node.js 20.x
    uses: actions/setup-node@v4
    with:
     node-version: 20.x
     cache: 'npm'
  - name: Install npm dependencies
    run: npm install

  - name: Start unit tests
    run: npm run test:unit

  - name: My SoftUni Username
    run: echo 'Todor_Zarkov'



 build-and-test-ui:
  runs-on: ubuntu-latest
  needs: build-and-test-unit

  steps:
  - name: Copy the source code
    uses: actions/Checkout@v4
  - name: Use Node.js 20.x
    uses: actions/setup-node@v4
    with:
     node-version: 20.x
     cache: 'npm'
  - name: Install npm dependencies
    run: npm install
  - name: Install browsers
    run: npx playwright install
  - name: Start the App
    run: npm start &
  - name: Start UI tests
    run: npm run test:ui

 deploy-on-render:
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  needs: build-and-test-ui
  steps:
   - name: Deploy to render
     uses: halfdomelabs/render-deploy@v0.1.2
     with:
      service-id: ${{secrets.RENDER_EXAM_PREP_II_ID}}
      render-token: ${{secrets.RENDER_EXAM_PREP_II_KEY}}